
trigger:
 branches:
  include:
    - main
pool:
 name: "Infra-Runners-pool"
 demands:
 - agent.name -equals 'myubuntuagent'

variables:
  imageName: 'loveable-image-grabber'
  dockerHubNamespace: 'prmd77'
  dockerHubPassword: $(DockerHubSecrets)
  dockerTag: 'latest'

stages:
- stage: build
  displayName: "Build Stage One"
  jobs:
    - job: BuildJob
      displayName: "Install and Build"
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: "Install Node.js"

        - script: |
            npm install
            npm run build
          displayName: "Install Dependencies and Build"

- stage: Dockerize
  displayName: "Docker Build and Push"
  dependsOn: build
  jobs:
    - job: DockerJob
      displayName: "Build Docker Image & Push to Docker Hub"
      steps:
        - task: Docker@2
          displayName: "Build and Push Docker Image"
          inputs:
            containerRegistry: 'DockerHubConnection'
            repository: '$(dockerHubNamespace)/$(imageName)'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(dockerTag)

     


        
       



  


